from __future__ import annotations

import json
from pathlib import Path

import nbformat as nbf


ROOT = Path(__file__).resolve().parent.parent
SOURCE_NB = ROOT / "L6-2_demo_crawler_pg.ipynb"
TARGET_NB = ROOT / "L7-1_demo_crawler_2D_PPO.ipynb"


def get_source_map():
    nb = json.loads(SOURCE_NB.read_text())
    return {idx: "".join(cell.get("source", [])) for idx, cell in enumerate(nb["cells"])}


def md(text: str):
    return nbf.v4.new_markdown_cell(text)


def code(text: str):
    return nbf.v4.new_code_cell(text)


def main():
    src = get_source_map()

    nb = nbf.v4.new_notebook()
    nb["metadata"]["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb["metadata"]["language_info"] = {"name": "python", "pygments_lexer": "ipython3"}

    cells = [
        md(
            "# PPO Demo on the Crawler\n\n"
            "This notebook keeps the **same crawler environment**, **same 10-seed setup**, and "
            "**same 600-episode experiment budget** used in Demo 7 of `L6-2_demo_crawler_pg.ipynb`.\n\n"
            "Main message:\n"
            "- On the current saved crawler outputs, PPO does **not** beat the best baseline variants in raw reward; the strongest crawler baseline remains higher.\n"
            "- PPO still shows the intended algorithmic effect: its raw advantage-variability proxy is much lower than the REINFORCE / baseline variants on this task, which is consistent with **better-conditioned updates**.\n"
            "- So this crawler notebook is best read as a bridge: it shows why PPO is attractive, but the clearer scaling story should come from a harder continuous-control task such as a **3D humanoid**.\n"
            "- To make the comparison fair and fast, we **load the previously saved REINFORCE / baseline / Actor-Critic checkpoints** whenever they are available, and only train PPO if its checkpoints are missing."
        ),
        code(
            "# Setup\n"
            "import numpy as np\n"
            "import mujoco\n"
            "import matplotlib.pyplot as plt\n"
            "from matplotlib import animation\n"
            "from IPython.display import HTML, display\n"
            "from pathlib import Path\n"
            "from io import BytesIO\n"
            "import base64\n"
            "import time\n"
            "import os\n\n"
            "import torch\n"
            "import torch.nn as nn\n"
            "import torch.optim as optim\n"
            "from torch.distributions import Normal\n\n"
            "print(f'MuJoCo version: {mujoco.__version__}')\n"
            "print(f'PyTorch version: {torch.__version__}')\n"
            "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
            "print(f'Device: {device}')\n"
            "print('Setup complete!')\n"
        ),
        code(src[2]),
        code(src[3]),
        code(src[5]),
        code(src[15]),
        md(
            "## Reuse the Demo 6 / Demo 7 results\n\n"
            "We keep the same seed list and same episode count as Demo 7.\n"
            "If the old checkpoints are present, the notebook loads them directly."
        ),
        code(src[11]),
        code(src[16]),
        md(
            "## PPO: Standalone Algorithm Focus\n\n"
            "Before comparing PPO against the older policy-gradient baselines, it helps to isolate the algorithm itself.\n"
            "The goal of this section is to answer three questions clearly:\n\n"
            "1. What are the **state, action, and reward** in this crawler setup?\n"
            "2. What extra ingredients does PPO add on top of Actor-Critic?\n"
            "3. How does the **clipped PPO update** map into code?\n\n"
            "**Setup at a glance**\n\n"
            "| Quantity | Notation | In this PPO demo |\n"
            "|---|---|---|\n"
            "| State | $s_t$ | 4D continuous crawler observation: arm angle, hand angle, arm angular velocity, hand angular velocity |\n"
            "| Action | $a_t$ | 2D continuous motor torques, one for each joint, clipped to $[-1, 1]$ |\n"
            "| Reward | $r_t$ | Forward torso velocity: $$r_t = \\frac{x_{t+1} - x_t}{\\Delta t}$$ |\n"
            "| Policy | $\\pi_\\theta(a\\mid s)$ | Gaussian actor with neural-network mean and learned log-standard-deviation |\n"
            "| Value baseline | $V_\\phi(s)$ | Critic network trained to predict return |\n"
            "| PPO-specific idea | $\\rho_t(\\theta)$ | Probability ratio is clipped so one update cannot move the policy too far |\n\n"
            "**What PPO changes relative to Demo 7**\n\n"
            "- Demo 7 already used a learned value baseline, so PPO is **not** starting from vanilla REINFORCE.\n"
            "- The new ingredient is the **clipped policy-ratio objective**: if the new policy wants to change action probabilities too aggressively, PPO truncates the update.\n"
            "- This usually lowers update variance and reduces destructive jumps, at the cost of sometimes being more conservative.\n\n"
            "**Pseudocode**\n\n"
            "```text\n"
            "initialize actor parameters θ and critic parameters ϕ\n"
            "for episode = 1, 2, ..., N:\n"
            "    run the current stochastic policy π_θ on the crawler\n"
            "    collect states s_t, actions a_t, rewards r_t, old log-probs log π_θ_old(a_t | s_t), values V_ϕ(s_t)\n\n"
            "    compute GAE advantages Â_t and return targets R_t\n"
            "    normalize the advantages within this batch\n\n"
            "    for several PPO epochs:\n"
            "        evaluate the current policy on the stored states/actions\n"
            "        compute ratio ρ_t = π_θ(a_t | s_t) / π_θ_old(a_t | s_t)\n"
            "        compute clipped actor objective:\n"
            "            L_actor = - mean( min(ρ_t Â_t, clip(ρ_t, 1-ε, 1+ε) Â_t) )\n"
            "        compute critic regression loss:\n"
            "            L_critic = mean( V_ϕ(s_t) - R_t )^2\n"
            "        update θ and ϕ with gradient descent\n"
            "```\n\n"
            "Recommended tuning order for this notebook:\n\n"
            "1. Fix the PPO action-probability bookkeeping so the stored `old_log_probs` match the actions actually sent to the environment.\n"
            "2. Increase the rollout batch size so each PPO update sees several episodes, not just one trajectory.\n"
            "3. If learning is still too slow, relax the clipping / update conservativeness.\n"
            "4. Only then sweep actor / critic learning rates and initial exploration scale.\n\n"
            "The code cells below implement those first two changes and put a runnable quick-sweep right after the standalone PPO block."
        ),
        code(
            "# ============================================================\n"
            "# PPO (clipped objective + value baseline)\n"
            "# ============================================================\n\n"
            "def compute_gae(rewards, values, gamma=0.99, lam=0.95):\n"
            "    rewards = np.asarray(rewards, dtype=np.float32)\n"
            "    values = np.asarray(values, dtype=np.float32)\n"
            "    advantages = np.zeros_like(rewards, dtype=np.float32)\n"
            "    gae = 0.0\n"
            "    next_value = 0.0\n"
            "    for t in reversed(range(len(rewards))):\n"
            "        delta = rewards[t] + gamma * next_value - values[t]\n"
            "        gae = delta + gamma * lam * gae\n"
            "        advantages[t] = gae\n"
            "        next_value = values[t]\n"
            "    returns = advantages + values\n"
            "    return advantages, returns\n\n\n"
            "def train_ppo(env, n_episodes=600, gamma=0.99, lam=0.95,\n"
            "              lr_actor=3e-4, lr_critic=1e-3, hidden=64,\n"
            "              clip_eps=0.2, train_epochs=4, minibatch_size=500,\n"
            "              batch_episodes=8, value_coef=0.5,\n"
            "              max_grad_norm=0.5, init_log_std=-1.0,\n"
            "              verbose=True, seed=None, checkpoint_label=None, checkpoint_meta=None):\n"
            "    if seed is not None:\n"
            "        torch.manual_seed(seed)\n"
            "        np.random.seed(seed)\n\n"
            "    actor = GaussianPolicy(env.obs_dim, env.act_dim, hidden, init_log_std=init_log_std).to(device)\n"
            "    critic = ValueNetwork(env.obs_dim, hidden).to(device)\n"
            "    actor_opt = optim.Adam(actor.parameters(), lr=lr_actor)\n"
            "    critic_opt = optim.Adam(critic.parameters(), lr=lr_critic)\n\n"
            "    rewards_history = []\n"
            "    adv_std_history = []\n\n"
            "    run_label = checkpoint_label or 'PPO'\n"
            "    t0 = time.time()\n"
            "    episodes_seen = 0\n"
            "    while episodes_seen < n_episodes:\n"
            "        batch_states = []\n"
            "        batch_actions = []\n"
            "        batch_old_log_probs = []\n"
            "        batch_advantages = []\n"
            "        batch_returns = []\n"
            "        episodes_this_batch = min(batch_episodes, n_episodes - episodes_seen)\n\n"
            "        for _ in range(episodes_this_batch):\n"
            "            obs = env.reset()\n"
            "            states = []\n"
            "            actions = []\n"
            "            rewards = []\n"
            "            old_log_probs = []\n"
            "            values = []\n\n"
            "            while True:\n"
            "                obs_t = torch.FloatTensor(obs).unsqueeze(0).to(device)\n"
            "                with torch.no_grad():\n"
            "                    action_t, log_prob_t = actor.get_action(obs_t)\n"
            "                    value_t = critic(obs_t)\n"
            "                action_np = action_t.squeeze(0).cpu().numpy()\n"
            "                next_obs, reward, terminated, truncated, _ = env.step(action_np)\n\n"
            "                states.append(obs)\n"
            "                actions.append(action_np)\n"
            "                rewards.append(reward)\n"
            "                old_log_probs.append(float(log_prob_t.item()))\n"
            "                values.append(float(value_t.item()))\n\n"
            "                obs = next_obs\n"
            "                if terminated or truncated:\n"
            "                    break\n\n"
            "            advantages_np, returns_np = compute_gae(rewards, values, gamma=gamma, lam=lam)\n"
            "            adv_std_history.append(float(np.std(advantages_np)) if len(advantages_np) > 1 else 0.0)\n"
            "            rewards_history.append(float(np.sum(rewards)))\n\n"
            "            batch_states.extend(states)\n"
            "            batch_actions.extend(actions)\n"
            "            batch_old_log_probs.extend(old_log_probs)\n"
            "            batch_advantages.extend(advantages_np.tolist())\n"
            "            batch_returns.extend(returns_np.tolist())\n"
            "            episodes_seen += 1\n\n"
            "        advantages_t = torch.FloatTensor(np.asarray(batch_advantages, dtype=np.float32)).to(device)\n"
            "        if len(advantages_t) > 1:\n"
            "            advantages_t = (advantages_t - advantages_t.mean()) / (advantages_t.std() + 1e-8)\n"
            "        returns_t = torch.FloatTensor(np.asarray(batch_returns, dtype=np.float32)).to(device)\n"
            "        states_t = torch.FloatTensor(np.asarray(batch_states, dtype=np.float32)).to(device)\n"
            "        actions_t = torch.FloatTensor(np.asarray(batch_actions, dtype=np.float32)).to(device)\n"
            "        old_log_probs_t = torch.FloatTensor(np.asarray(batch_old_log_probs, dtype=np.float32)).to(device)\n\n"
            "        n = len(batch_states)\n"
            "        idx = np.arange(n)\n"
            "        effective_minibatch = min(minibatch_size, n)\n"
            "        for _ in range(train_epochs):\n"
            "            np.random.shuffle(idx)\n"
            "            for start in range(0, n, effective_minibatch):\n"
            "                mb_idx = idx[start:start + effective_minibatch]\n"
            "                mb_states = states_t[mb_idx]\n"
            "                mb_actions = actions_t[mb_idx]\n"
            "                mb_old_log_probs = old_log_probs_t[mb_idx]\n"
            "                mb_advantages = advantages_t[mb_idx]\n"
            "                mb_returns = returns_t[mb_idx]\n\n"
            "                new_log_probs = actor.evaluate(mb_states, mb_actions)\n"
            "                ratio = torch.exp(new_log_probs - mb_old_log_probs)\n"
            "                clipped_ratio = torch.clamp(ratio, 1.0 - clip_eps, 1.0 + clip_eps)\n"
            "                actor_loss = -torch.min(ratio * mb_advantages, clipped_ratio * mb_advantages).mean()\n\n"
            "                actor_opt.zero_grad()\n"
            "                actor_loss.backward()\n"
            "                nn.utils.clip_grad_norm_(actor.parameters(), max_grad_norm)\n"
            "                actor_opt.step()\n\n"
            "                value_pred = critic(mb_states)\n"
            "                critic_loss = value_coef * nn.functional.mse_loss(value_pred, mb_returns)\n"
            "                critic_opt.zero_grad()\n"
            "                critic_loss.backward()\n"
            "                nn.utils.clip_grad_norm_(critic.parameters(), max_grad_norm)\n"
            "                critic_opt.step()\n\n"
            "        if verbose and episodes_seen % 100 == 0:\n"
            "            avg_r = np.mean(rewards_history[-50:])\n"
            "            avg_adv_std = np.mean(adv_std_history[-50:])\n"
            "            print(f'  {run_label} | Episode {episodes_seen:4d} | Avg reward: {avg_r:7.1f} | avg std(A): {avg_adv_std:7.2f}')\n\n"
            "    elapsed = time.time() - t0\n"
            "    if verbose:\n"
            "        print(f'  Training completed in {elapsed:.1f}s')\n\n"
            "    if checkpoint_label is not None:\n"
            "        meta = {\n"
            "            'obs_dim': int(env.obs_dim),\n"
            "            'act_dim': int(env.act_dim),\n"
            "            'hidden': int(hidden),\n"
            "            'critic_hidden': int(hidden),\n"
            "            'batch_episodes': int(batch_episodes),\n"
            "            'clip_eps': float(clip_eps),\n"
            "            'train_epochs': int(train_epochs),\n"
            "            'lr_actor': float(lr_actor),\n"
            "            'lr_critic': float(lr_critic),\n"
            "            'init_log_std': float(init_log_std),\n"
            "        }\n"
            "        if checkpoint_meta:\n"
            "            meta.update(checkpoint_meta)\n"
            "        save_pg_checkpoint({\n"
            "            'kind': 'ppo',\n"
            "            'label': checkpoint_label,\n"
            "            'meta': meta,\n"
            "            'policy_state_dict': actor.state_dict(),\n"
            "            'critic_state_dict': critic.state_dict(),\n"
            "            'rewards': np.asarray(rewards_history, dtype=np.float32),\n"
            "            'extras': {\n"
            "                'adv_std_history': np.asarray(adv_std_history, dtype=np.float32),\n"
            "            },\n"
            "        })\n\n"
            "    return actor, critic, rewards_history, adv_std_history\n"
        ),
        md(
            "## PPO Tuning Runner\n\n"
            "Run this quick sweep immediately after the standalone PPO definition if you want to test the tuning knobs before doing the full lecture comparison.\n\n"
            "Suggested workflow:\n"
            "- Start with 3 to 4 seeds and compare all presets on the same plot.\n"
            "- If one configuration is clearly better, promote only that winner to a wider confirmation run.\n"
            "- Treat the selected PPO config below as the representative one for the later comparison cells.\n"
        ),
        code(
            "# ============================================================\n"
            "# PPO benchmark on the shared crawler protocol\n"
            "# ============================================================\n\n"
            "PPO_TUNING_CONFIG = {\n"
            "    'n_episodes': compare_episodes,\n"
            "    'batch_episodes': 8,\n"
            "    'clip_eps': 0.2,\n"
            "    'train_epochs': 4,\n"
            "    'minibatch_size': 500,\n"
            "    'lr_actor': 3e-4,\n"
            "    'lr_critic': 1e-3,\n"
            "    'value_coef': 0.5,\n"
            "    'max_grad_norm': 0.5,\n"
            "    'init_log_std': -1.0,\n"
            "}\n\n"
            "PPO_SWEEP_PRESETS = [\n"
            "    {\n"
            "        'name': 'batch8_clip0.2_epochs4_lr3e-4_1e-3_std-1.0',\n"
            "        **PPO_TUNING_CONFIG,\n"
            "    },\n"
            "    {\n"
            "        'name': 'batch8_clip0.25_epochs4_lr3e-4_1e-3_std-1.0',\n"
            "        **PPO_TUNING_CONFIG,\n"
            "        'clip_eps': 0.25,\n"
            "    },\n"
            "    {\n"
            "        'name': 'batch8_clip0.2_epochs8_lr3e-4_1e-3_std-1.0',\n"
            "        **PPO_TUNING_CONFIG,\n"
            "        'train_epochs': 8,\n"
            "    },\n"
            "    {\n"
            "        'name': 'batch16_clip0.2_epochs4_lr1e-4_3e-4_std-1.0',\n"
            "        **PPO_TUNING_CONFIG,\n"
            "        'batch_episodes': 16,\n"
            "        'lr_actor': 1e-4,\n"
            "        'lr_critic': 3e-4,\n"
            "    },\n"
            "]\n\n"
            "print(f\"=== L7-1: PPO on the same crawler ({len(range(4))} quick-sweep seeds) ===\")\n"
            "print('Actor: Gaussian policy')\n"
            "print('Critic: learned value baseline V(s)')\n"
            "print('Extra idea: clipped policy-ratio update for more stable policy improvement')\n"
            "ppo_seeds = list(range(4))\n"
            "ppo_sweep_results = {}\n"
            "ppo_curve_colors = ['tab:red', 'tab:orange', 'tab:green', 'tab:purple', 'tab:brown', 'tab:pink']\n\n"
            "for ppo_config in PPO_SWEEP_PRESETS:\n"
            "    ppo_config = ppo_config.copy()\n"
            "    ppo_episodes = ppo_config['n_episodes']\n"
            "    print(f\"\\n=== PPO config: {ppo_config['name']} ===\")\n"
            "    config_results = {\n"
            "        'config': ppo_config.copy(),\n"
            "        'policies_by_seed': {},\n"
            "        'critics_by_seed': {},\n"
            "        'reward_histories_by_seed': {},\n"
            "        'adv_std_histories_by_seed': {},\n"
            "    }\n\n"
            "    for seed in ppo_seeds:\n"
            "        env_ppo = CrawlerEnv()\n"
            "        ppo_meta = {\n"
            "            'demo': 'L7-1',\n"
            "            'variant': 'ppo',\n"
            "            'seed': seed,\n"
            "            'n_episodes': ppo_episodes,\n"
            "            'batch_episodes': ppo_config['batch_episodes'],\n"
            "            'clip_eps': ppo_config['clip_eps'],\n"
            "            'train_epochs': ppo_config['train_epochs'],\n"
            "            'lr_actor': ppo_config['lr_actor'],\n"
            "            'lr_critic': ppo_config['lr_critic'],\n"
            "            'init_log_std': ppo_config['init_log_std'],\n"
            "            'config_name': ppo_config['name'],\n"
            "        }\n"
            "        ppo_checkpoint_label = f\"L7-1: PPO [{ppo_config['name']}] (seed {seed})\"\n"
            "        latest = maybe_load_pg_checkpoint(\n"
            "            kind='ppo',\n"
            "            obs_dim=env_ppo.obs_dim,\n"
            "            act_dim=env_ppo.act_dim,\n"
            "            hidden=64,\n"
            "            label=ppo_checkpoint_label,\n"
            "            extra_meta=ppo_meta,\n"
            "            with_critic=True,\n"
            "        )\n"
            "        if latest is None:\n"
            "            print(f'  Seed {seed}: training')\n"
            "            actor_seed, critic_seed, rewards_seed, adv_std_seed = train_ppo(\n"
            "                env_ppo,\n"
            "                n_episodes=ppo_episodes,\n"
            "                batch_episodes=ppo_config['batch_episodes'],\n"
            "                clip_eps=ppo_config['clip_eps'],\n"
            "                train_epochs=ppo_config['train_epochs'],\n"
            "                minibatch_size=ppo_config['minibatch_size'],\n"
            "                lr_actor=ppo_config['lr_actor'],\n"
            "                lr_critic=ppo_config['lr_critic'],\n"
            "                value_coef=ppo_config['value_coef'],\n"
            "                max_grad_norm=ppo_config['max_grad_norm'],\n"
            "                init_log_std=ppo_config['init_log_std'],\n"
            "                seed=seed,\n"
            "                verbose=True,\n"
            "                checkpoint_label=ppo_checkpoint_label,\n"
            "                checkpoint_meta=ppo_meta,\n"
            "            )\n"
            "        else:\n"
            "            print(f'  Seed {seed}: loaded')\n"
            "            actor_seed, critic_seed, rewards_seed, extras = latest\n"
            "            adv_std_seed = list(extras.get('adv_std_history', []))\n\n"
            "        config_results['policies_by_seed'][seed] = actor_seed\n"
            "        config_results['critics_by_seed'][seed] = critic_seed\n"
            "        config_results['reward_histories_by_seed'][seed] = rewards_seed\n"
            "        config_results['adv_std_histories_by_seed'][seed] = adv_std_seed\n\n"
            "    ppo_sweep_results[ppo_config['name']] = config_results\n\n"
            "fig, ax = plt.subplots(figsize=(11, 5))\n"
            "for idx, (config_name, config_results) in enumerate(ppo_sweep_results.items()):\n"
            "    plot_seed_average(\n"
            "        ax,\n"
            "        list(config_results['reward_histories_by_seed'].values()),\n"
            "        color=ppo_curve_colors[idx % len(ppo_curve_colors)],\n"
            "        label=config_name,\n"
            "        window=40,\n"
            "        alpha=0.12,\n"
            "    )\n"
            "ax.set_title('PPO quick sweep: reward curves by configuration', fontsize=13, fontweight='bold')\n"
            "ax.set_xlabel('Episode')\n"
            "ax.set_ylabel('Total Reward')\n"
            "ax.grid(True, alpha=0.3)\n"
            "ax.legend(fontsize=9)\n"
            "plt.tight_layout()\n"
            "plt.show()\n\n"
            "print('Final PPO config comparison across quick-sweep seeds (last 50 episodes):')\n"
            "for config_name, config_results in ppo_sweep_results.items():\n"
            "    reward_mean, reward_std = summarize_final_window(\n"
            "        list(config_results['reward_histories_by_seed'].values()),\n"
            "        tail=50,\n"
            "    )\n"
            "    print(f'{config_name:45s} | reward: {reward_mean:6.1f} +/- {reward_std:4.1f}')\n\n"
            "best_ppo_config_name = max(\n"
            "    ppo_sweep_results,\n"
            "    key=lambda name: summarize_final_window(\n"
            "        list(ppo_sweep_results[name]['reward_histories_by_seed'].values()),\n"
            "        tail=50,\n"
            "    )[0],\n"
            ")\n"
            "ppo_results = ppo_sweep_results[best_ppo_config_name]\n"
            "ppo_config = ppo_results['config'].copy()\n"
            "print(f\"\\nSelected PPO config for downstream cells: {best_ppo_config_name}\")\n\n"
            "ppo_seed = max(\n"
            "    ppo_results['reward_histories_by_seed'],\n"
            "    key=lambda s: np.mean(ppo_results['reward_histories_by_seed'][s][-50:])\n"
            ")\n"
            "ppo_actor = ppo_results['policies_by_seed'][ppo_seed]\n"
            "ppo_critic = ppo_results['critics_by_seed'][ppo_seed]\n"
            "rewards_ppo = ppo_results['reward_histories_by_seed'][ppo_seed]\n"
            "adv_std_ppo = ppo_results['adv_std_histories_by_seed'][ppo_seed]\n"
            "print(f'Using seed {ppo_seed} as the representative PPO policy for rollout cells.')\n"
        ),
        code(
            "# PPO vs previous baselines on the same crawler protocol\n"
            "fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n"
            "window = 40\n\n"
            "ax = axes[0]\n"
            "for label, result in baseline_results.items():\n"
            "    plot_seed_average(\n"
            "        ax,\n"
            "        list(result['reward_histories_by_seed'].values()),\n"
            "        color=result['color'],\n"
            "        label=label,\n"
            "        window=window,\n"
            "    )\n"
            "plot_seed_average(\n"
            "    ax,\n"
            "    list(actor_critic_results['reward_histories_by_seed'].values()),\n"
            "    color='tab:blue',\n"
            "    label='Actor-Critic (learned $V(s)$)',\n"
            "    window=window,\n"
            ")\n"
            "plot_seed_average(\n"
            "    ax,\n"
            "    list(ppo_results['reward_histories_by_seed'].values()),\n"
            "    color='tab:red',\n"
            "    label='PPO (clipped objective)',\n"
            "    window=window,\n"
            ")\n"
            "ax.set_title('Reward curves: mean +/- 1 std over 10 seeds', fontsize=13, fontweight='bold')\n"
            "ax.set_xlabel('Episode')\n"
            "ax.set_ylabel('Total Reward')\n"
            "ax.legend(fontsize=11)\n"
            "ax.grid(True, alpha=0.3)\n\n"
            "ax = axes[1]\n"
            "for label, result in baseline_results.items():\n"
            "    plot_seed_average(\n"
            "        ax,\n"
            "        list(result['adv_std_histories_by_seed'].values()),\n"
            "        color=result['color'],\n"
            "        label=label,\n"
            "        window=window,\n"
            "    )\n"
            "plot_seed_average(\n"
            "    ax,\n"
            "    list(actor_critic_results['adv_std_histories_by_seed'].values()),\n"
            "    color='tab:blue',\n"
            "    label='Actor-Critic (learned $V(s)$)',\n"
            "    window=window,\n"
            ")\n"
            "plot_seed_average(\n"
            "    ax,\n"
            "    list(ppo_results['adv_std_histories_by_seed'].values()),\n"
            "    color='tab:red',\n"
            "    label='PPO (raw GAE advantage std)',\n"
            "    window=window,\n"
            ")\n"
            "ax.set_xlabel('Episode')\n"
            "ax.set_ylabel('Std of raw advantage weights')\n"
            "ax.set_title('Variance proxy: mean +/- 1 std over 10 seeds', fontsize=13, fontweight='bold')\n"
            "ax.legend(fontsize=11)\n"
            "ax.grid(True, alpha=0.3)\n\n"
            "plt.tight_layout()\n"
            "plt.show()\n\n"
            "print('Final comparison across 10 seeds (last 50 episodes):')\n"
            "for label, result in baseline_results.items():\n"
            "    reward_mean, reward_std = summarize_final_window(list(result['reward_histories_by_seed'].values()), tail=50)\n"
            "    var_mean, var_std = summarize_final_window(list(result['adv_std_histories_by_seed'].values()), tail=50)\n"
            "    print(f'{label:24s} | reward: {reward_mean:6.1f} +/- {reward_std:4.1f} | std: {var_mean:6.2f} +/- {var_std:4.2f}')\n\n"
            "ac_reward_mean, ac_reward_std = summarize_final_window(list(actor_critic_results['reward_histories_by_seed'].values()), tail=50)\n"
            "ac_var_mean, ac_var_std = summarize_final_window(list(actor_critic_results['adv_std_histories_by_seed'].values()), tail=50)\n"
            "print(f\"{'Actor-Critic (learned)':24s} | reward: {ac_reward_mean:6.1f} +/- {ac_reward_std:4.1f} | std: {ac_var_mean:6.2f} +/- {ac_var_std:4.2f}\")\n\n"
            "ppo_reward_mean, ppo_reward_std = summarize_final_window(list(ppo_results['reward_histories_by_seed'].values()), tail=50)\n"
            "ppo_var_mean, ppo_var_std = summarize_final_window(list(ppo_results['adv_std_histories_by_seed'].values()), tail=50)\n"
            "print(f\"{'PPO (clipped objective)':24s} | reward: {ppo_reward_mean:6.1f} +/- {ppo_reward_std:4.1f} | std: {ppo_var_mean:6.2f} +/- {ppo_var_std:4.2f}\")\n"
        ),
        code(
            "# 10-second rollout of the representative PPO policy\n"
            "env_eval_ppo = CrawlerEnv()\n\n"
            "def ppo_policy(obs):\n"
            "    with torch.no_grad():\n"
            "        obs_t = torch.FloatTensor(obs).unsqueeze(0).to(device)\n"
            "        mu, _ = ppo_actor(obs_t)\n"
            "        return mu.squeeze(0).cpu().numpy()\n\n"
            "frames_ppo, dist_ppo, _ = eval_policy(env_eval_ppo, ppo_policy, 'L7-1: PPO')\n"
            "show_video(frames_ppo, title=f'PPO — {dist_ppo:.2f}m in 10s')\n"
        ),
        code(
            "# Final comparison: representative policies from the policy-gradient family\n"
            "policy_panels = []\n"
            "comparison_results = {}\n\n"
            "def add_policy_panel(label, policy_fn, *, env=None, video_title=None, max_steps=500,\n"
            "                     frames=None, dist=None):\n"
            "    if frames is None or dist is None:\n"
            "        if env is None:\n"
            "            env = CrawlerEnv(max_steps=max_steps)\n"
            "        frames, dist, _ = eval_policy(env, policy_fn, label, max_steps=max_steps)\n"
            "    comparison_results[label] = dist\n"
            "    video_html = show_video(frames, title=video_title or f'{label} — {dist:.2f}m in 10s').data\n"
            "    policy_panels.append({\n"
            "        'label': label,\n"
            "        'distance': dist,\n"
            "        'video_html': video_html,\n"
            "    })\n\n"
            "def representative_seed(history_dict):\n"
            "    return max(history_dict, key=lambda s: np.mean(history_dict[s][-50:]))\n\n"
            "def make_comparison_plot_base64(results_dict, title='Policy Comparison: Distance Traveled in 10s'):\n"
            "    labels = list(results_dict.keys())\n"
            "    dists = list(results_dict.values())\n"
            "    colors = ['#d9534f' if d < 0.5 else '#5bc0de' if d < 1.5 else '#5cb85c' for d in dists]\n"
            "    fig, ax = plt.subplots(figsize=(9, max(4, len(labels) * 0.55 + 1.2)))\n"
            "    bars = ax.barh(labels, dists, color=colors, edgecolor='white', height=0.6)\n"
            "    ax.set_xlabel('Distance (m)')\n"
            "    ax.set_title(title, fontsize=14, fontweight='bold')\n"
            "    ax.axvline(x=0, color='gray', linewidth=0.5)\n"
            "    for bar, d in zip(bars, dists):\n"
            "        ax.text(bar.get_width() + 0.05, bar.get_y() + bar.get_height()/2,\n"
            "                f'{d:.2f}m', va='center', fontsize=11)\n"
            "    ax.invert_yaxis()\n"
            "    plt.tight_layout()\n"
            "    buf = BytesIO()\n"
            "    fig.savefig(buf, format='png', dpi=160, bbox_inches='tight')\n"
            "    plt.close(fig)\n"
            "    return base64.b64encode(buf.getvalue()).decode('ascii')\n\n"
            "reinforce_meta = {\n"
            "    'demo': '5',\n"
            "    'variant': 'reinforce',\n"
            "    'n_episodes': 4500,\n"
            "}\n"
            "env_tmp = CrawlerEnv()\n"
            "loaded = maybe_load_pg_checkpoint(\n"
            "    kind='reinforce',\n"
            "    obs_dim=env_tmp.obs_dim,\n"
            "    act_dim=env_tmp.act_dim,\n"
            "    hidden=64,\n"
            "    label='Demo 5: REINFORCE',\n"
            "    extra_meta=reinforce_meta,\n"
            ")\n"
            "if loaded is None:\n"
            "    raise RuntimeError('Expected the Demo 5 REINFORCE checkpoint to exist, but none was found.')\n"
            "policy_reinforce, rewards_reinforce, reinforce_extras = loaded\n\n"
            "def reinforce_policy(obs):\n"
            "    with torch.no_grad():\n"
            "        obs_t = torch.FloatTensor(obs).unsqueeze(0).to(device)\n"
            "        mu, _ = policy_reinforce(obs_t)\n"
            "        return mu.squeeze(0).cpu().numpy()\n\n"
            "const_seed = representative_seed(baseline_results['Constant baseline']['reward_histories_by_seed'])\n"
            "const_policy_model = baseline_results['Constant baseline']['policies_by_seed'][const_seed]\n"
            "def constant_baseline_policy(obs):\n"
            "    with torch.no_grad():\n"
            "        obs_t = torch.FloatTensor(obs).unsqueeze(0).to(device)\n"
            "        mu, _ = const_policy_model(obs_t)\n"
            "        return mu.squeeze(0).cpu().numpy()\n\n"
            "time_seed = representative_seed(baseline_results['Time-dependent baseline']['reward_histories_by_seed'])\n"
            "time_policy_model = baseline_results['Time-dependent baseline']['policies_by_seed'][time_seed]\n"
            "def time_baseline_policy(obs):\n"
            "    with torch.no_grad():\n"
            "        obs_t = torch.FloatTensor(obs).unsqueeze(0).to(device)\n"
            "        mu, _ = time_policy_model(obs_t)\n"
            "        return mu.squeeze(0).cpu().numpy()\n\n"
            "def actor_critic_policy(obs):\n"
            "    with torch.no_grad():\n"
            "        obs_t = torch.FloatTensor(obs).unsqueeze(0).to(device)\n"
            "        mu, _ = actor_ac(obs_t)\n"
            "        return mu.squeeze(0).cpu().numpy()\n\n"
            "if 'frames_ppo' in globals() and 'dist_ppo' in globals():\n"
            "    add_policy_panel('L7-1: PPO', ppo_policy, video_title='PPO', frames=frames_ppo, dist=dist_ppo)\n"
            "else:\n"
            "    add_policy_panel('L7-1: PPO', ppo_policy, video_title='PPO')\n"
            "add_policy_panel('Demo 5: REINFORCE', reinforce_policy, video_title='REINFORCE')\n"
            "add_policy_panel('Demo 6: Constant baseline', constant_baseline_policy, video_title='Constant baseline')\n"
            "add_policy_panel('Demo 6: Time baseline', time_baseline_policy, video_title='Time-dependent baseline')\n"
            "add_policy_panel('Demo 7: Actor-Critic', actor_critic_policy, video_title='Actor-Critic')\n\n"
            "plot_png = make_comparison_plot_base64(comparison_results)\n"
            "cards_html = ''.join(\n"
            "    f\"<div style='background:#fff;border:1px solid #ddd;border-radius:10px;padding:10px;'>\"\n"
            "    f\"<div style='font-weight:600;margin-bottom:8px'>{panel['label']} ({panel['distance']:.2f}m)</div>\"\n"
            "    f\"{panel['video_html']}\"\n"
            "    f\"</div>\"\n"
            "    for panel in policy_panels\n"
            ")\n"
            "display(HTML(\n"
            "    f\"\"\"\n"
            "<div style='display:grid;grid-template-columns:minmax(340px, 420px) 1fr;gap:20px;align-items:start;'>\n"
            "  <div style='background:#fff;border:1px solid #ddd;border-radius:10px;padding:12px;'>\n"
            "    <div style='font-weight:700;font-size:18px;margin-bottom:10px;'>Distance traveled in 10 seconds</div>\n"
            "    <img src='data:image/png;base64,{plot_png}' style='width:100%;height:auto;display:block;' />\n"
            "  </div>\n"
            "  <div style='display:flex;flex-direction:column;gap:16px;'>\n"
            "    {cards_html}\n"
            "  </div>\n"
            "</div>\n"
            "\"\"\"\n"
            "))\n"
        ),
        md(
            "## Reading the result\n\n"
            "The quantity on the right is not a formal variance proof. It is a practical proxy: the standard deviation of the **raw advantage weights** used before normalization.\n\n"
            "What the current saved output actually shows:\n"
            "- The current PPO tuning sweep is only a **1-seed quick sweep**, so the PPO config ranking itself is still provisional.\n"
            "- Within that saved sweep, the best PPO preset is `batch8_clip0.2_epochs8_lr1e-3_1e-3_std-1.0`, reaching about **24.9** average reward over the last 50 episodes and about **0.48 m** in the 10-second rollout.\n"
            "- On this crawler task, PPO is **not** the top performer in raw reward: the saved comparison reports about **35.1** for the time-dependent baseline, **33.3** for the constant baseline, **31.5** for Actor-Critic, **29.7** for vanilla REINFORCE, and **24.9** for PPO.\n"
            "- PPO's strongest evidence here is the variance proxy: its raw advantage std is about **0.57**, versus **1.28** for the time-dependent baseline and roughly **1.78 to 2.01** for the other policy-gradient baselines. So on the crawler, PPO currently looks more like a **variance-control method** than a raw-performance win.\n\n"
            "Additional learning objective: scaling beyond the crawler\n"
            "- The crawler is still a small 2D task with only 2 continuous actions. That is useful for understanding the algorithm, but it is not yet the setting where PPO should be expected to show its biggest practical advantage.\n"
            "- A better next comparison is a harder continuous-control environment such as a **Humanoid 3D** task, where the action space is much larger, trajectories are longer, and credit assignment is harder.\n"
            "- The notebook should therefore add three follow-on demos: `REINFORCE` on Humanoid 3D, `REINFORCE with baseline / Actor-Critic` on Humanoid 3D, and `PPO` on Humanoid 3D, all evaluated with the same rollout metric and aligned training-curve plots.\n"
            "- The intended lesson is that as the task becomes more complex, REINFORCE-style methods tend to **flatten** or become too noisy, while PPO's clipped updates can keep learning moving and scale more gracefully.\n"
            "- In other words, the crawler notebook motivates the mechanism, and the humanoid demo should supply the stronger scaling evidence."
        ),
    ]

    nb["cells"] = cells
    TARGET_NB.write_text(nbf.writes(nb))
    print(f"Wrote {TARGET_NB}")


if __name__ == "__main__":
    main()
